### PR TITLE
button class, button positions, click handlers improvements, better focus-el selection

### PR DESCRIPTION
**Pull request by AhsanAyaz**
top-right,top-left,bottom-right,bottom-left
included a property {{doneButtonClass}} to support flexible class assignment through the attributes of directives (for custom button styling)
Changed "focusElementId" to "focusElementSelector" for more flexible queries and focus element possibilities e.g. "myDiv .customLI:first .icon.right"
So now, to focus an element having id "myBtn", the selector passed should be "#myBtn"

### CODE REVIEW

**Comment by souly1** [comment]
Hi Ahsan, thanks for the pull request and changes, 
But I currently cannot approve this, the tests fail and the new code is missing new tests.
In addition, the code would require testing and regression testing for the different types of walkthroughs...

**Comment by AhsanAyaz** [comment]
Hey Ophir. 
Thanks for the response.. Do let me know if you can work out the tests or want me to do it. 
I might be able to do this when I'll get time. 
Thanks !

**Comment by souly1** [comment]
Very well, I won't be able to work out the tests so it will fall on you to work them out, but before you do - looking at the changes you've done, they all seem great but what happens with 'focusElementSelector' when multiple items are a good fit for the query reply (for example: two elements with same class where class is selector)? given the current implementation I believe we can't support multiple items to focus on, so perhaps an exception or error message in console when query retrieves more than one item? 
Also, given the new behaviour of the selector we can either support current selector behaviour (e.g, with #) for backward compatibility, perhaps with deprecation message when we receive such a selector, or if we think the mix might cause issues bump up the minor version (still pre-release so we'll just bump minor) as it is a breaking change.
what are your thoughts on the two points mentioned?

**Comment by AhsanAyaz** [comment]
You've got a good point there about multiple elements potentially being focused right now. I'd recommend the first option. Introducing the new selector with backward compatibility. Throwing an error on receiving multiple elements (or maybe focusing the first element from the result).Because it's better, easily adaptable and will give us more time to think over the possibilities that the new behavior can produce for future release.
I'll surely work out with the tests and will let you know.
Let me know your thoughts on this.

**Comment by souly1** [comment]
Sounds like a good solution, awaiting to hear from you,
Thanks again, sounds like a cool addition.

**Pull request closed without merging**
