### PR TITLE
add sass file

### PR DESCRIPTION
**Pull request by reiaguilera**
add scss file

### CODE REVIEW

**Comment by reiaguilera** [comment]
add gulp files, git ignored,

**Comment by reiaguilera** [comment]
add example page

**Comment by souly1** [comment]
Hi @reiaguilera , thanks for adding the sass and copying the example from plunker and adding it to the project here.
Question, why should we have both sass and css when css should be enough, won't having both require managing two versions? 
Thanks again

**Comment by reiaguilera** [comment]
hi @souly1 , the css and min.css files is generated automatically through a gulp task, this allows the styles to be more dynamic and manageable again. thx for answering: D

**Pull request closed without merging**
