### PR TITLE
Watching focusElementSelector

### PR DESCRIPTION
**Pull request by hefler**
Watching focusElementSelector, this allows to dynamically change an element.

### CODE REVIEW

**Comment by souly1** [comment]
It seems this checkin is causing tests to fail... as long as they're failing I cannot check this in...

**Comment by hefler** [comment]
I'm not familiar with testing. So I don't understand what I need to do in order for the get it passing the test. 🙄

**Comment by hefler** [comment]
Found the problem!

**Comment by souly1** [comment]
Great! thanks @hefler!

**Pull request merged**
